language: node_js
node_js: node
branches:
  only:
  - master
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run build && npm run test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev